### ISSUE TITLE
How to compile on Ubuntu trusty or xenial?

### ISSUE THREAD

**Issue by probonopd** [jgaa/darkspeak#4]
I am trying to build continuous builds on Travis CI and to produce AppImages. However, I am running into compilation issues. What am I doing wrong?

Here is my current work:
https://github.com/probonopd/darkspeak/blob/patch-1/.travis.yml

Here is the build log:
https://api.travis-ci.com/v3/job/199402718/log.txt

The first error I see is:

```
error: crypto_sign_state was not declared in this scope
```

**Comment by jgaa** [comment]
I have only built it on my develop machines this far, and only with the latest Qt develop. 

May be it's time to to set up automatic builds to make sure it works well on all target platforms. I will make an appimage for this application.

**Comment by jgaa** [comment]
The application compiles with QT 5.93, but does not run, as it require QML 5.12 controls. 
I will not deal with that now, but work to get a Beta ready. When the code is there, I'll look at how to build it on CI systems. Worst case is to build QT 5.12 from source as part of the build. I can probably avoid that on my own build machine, by exposing a downloaded QT 5.12 library to the build containers.

**Comment by probonopd** [comment]
> I have only built it on my develop machines this far

Which exact OS and compiler versions?

**Comment by probonopd** [comment]
Despite using Qt 5.12 on xenial, still getting `error: ‘crypto_sign_state’ was not declared in this scope`.

**Comment by probonopd** [comment]
Also with Qt 5.12 and gcc-8, getting

```
In file included from include/ds/message.h:10,
                 from include/ds/dsengine.h:10,
                 from src/dsengine.cpp:7:
../cryptolib/include/ds/dscert.h: In member function ‘void ds::crypto::DsCert::sign(Tsign&, std::initializer_list<T>) const’:
../cryptolib/include/ds/dscert.h:83:9: error: ‘crypto_sign_state’ was not declared in this scope
```

I doubt this has to do with compiler or Qt versions...

**Comment by jgaa** [comment]
g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic  

And building with Qt Creator 4.9.0 and Qt 5.12.2

**Comment by probonopd** [comment]
Can you try on xenial? bionic is not the oldest still-supported LTS release.

> And building with Qt Creator 4.9.0 and Qt 5.12.2

I am using Qt 5.12 without Qt Creator because I am building on Travis CI rather than on a local desktop.

**Comment by jgaa** [comment]
g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic  

And building with Qt Creator 4.9.0 and Qt 5.12.2
